# CONTRIBUTING.md里建议采用的方式
ARG BASE_VERSION=9.4.0-2.2.5
FROM container-registry.oracle.com/mysql/community-operator:$BASE_VERSION
# 文档里给的指令是错的, 第二个参数少了mysqloperator/
COPY mysqloperator/ /usr/lib/mysqlsh/python-packages/mysqloperator/